//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectList
    {
        public int ProjectId { get; set; }
        public string Title { get; set; }
        public string ProjectDescription { get; set; }
        public Nullable<int> TotalMarks { get; set; }
        public Nullable<int> StudentsAllowed { get; set; }
    }
}
